version: 2.1

jobs:
  test:
    docker:
      - image: jonbaldie/joy:latest
    steps:
      - run: pwd | grep '/usr/src/app'
      - run: which janet | grep '/usr/local/bin/janet'
      - run: which jpm | grep '/usr/local/bin/jpm'
      - run: which joy | grep '/usr/local/bin/joy'
      - run: which entr | grep '/usr/local/bin/entr'
      - run: joy new foo && ls foo

workflows:
  build_and_test:
    jobs:
      - test
